### ISSUE TITLE
Checks not received by TBBK

### ISSUE THREAD

**Issue by rachaelwoolen** [seedco/highpri#2] opened 2017-05-08 22:59 UTC
### Business impacted
Midwest Benefits LLC

### Last 4 digits of Acct Number
0563

### Customer name who reported issue
Michael Wilson

### Issue described
Check deposited 4/28 for $277.03 is still pending. Can we see why?

**Comment by tn-** [comment] 2017-05-08 23:35
We're currently following up with Bancorp to resolve the issue.

**Comment by melgeyer** [comment] 2017-05-09 14:15
cool, thanks for the update, @tn- . 

I updated Mike b/c he was requesting more info. He's currently using this ticket thread but he's highly likely to use a new one at some point today (I'll update as needed): https://seedinc.zendesk.com/agent/tickets/805

**Comment by melgeyer** [comment] 2017-05-09 16:47
As far as we can tell from Terri's report of the checks she's seen in deposit files from 4/24 to 5/1, there are some checks which were not sent to Bancorp. 

1. Obsidian (x084) deposited check number: 2010 in the amount of $978.80 on 4/25

2. Conkuer (x183) deposited check number: 258560 in the amount of $3,000.00 on 4/27

3. Midwest Benefits (x563) deposited check number: 0000230151 in the amount of $277.03 on 4/28

4. Viktor Radchenko (x696) deposited check number: 1112 in the amount of $1000.00 on 5/1

5. Rachael Woolen (x779) deposited check number: 0000001001 in the amount of $1.02 on 5/1

We got to get these pushed to tbbk today if possible because they are already a week old or older. In the meantime, I'll hit up the customers and let them know there was a snag and we'll be resolving it as soon as we can. 

cc: @jcai - any way to tell which file was compromised? Either our send to Cachet or their file send to TBBK?

**Comment by john-cai** [comment] 2017-05-09 17:02
@melgeyer all of these checks were approved in the check review tool, which means our send to cachet was successful. we'll follow up with our contacts at cachet to see what happened.

**Comment by melgeyer** [comment] 2017-05-09 17:05
@lh12345 can you please ask Cachet what's up? I'm also happy to do this if you'd like to send over the appropriate contact info.

**Comment by john-cai** [comment] 2017-05-09 17:05
@melgeyer @lh12345 I can do this since I'm the main contact for Cachet for the RDC project

**Comment by melgeyer** [comment] 2017-05-09 17:08
Awesome, sounds great! Please let them know this is an urgent issue for us since our customers have already been waiting more than a week for these check deposits. thanks!

**Comment by john-cai** [comment] 2017-05-09 17:53
i filed a ticket with cachet, and also checked with our system. It turns out all of the checks other than 3. have settled, so I'm not sure why bancorp told us that those transactions didn't get received.

for the midwest one, cachet is looking into it

**Comment by lh12345** [comment] 2017-05-09 17:55
@melgeyer Terri's response was confirming what she saw in terms of deposits for Midwest Benefit's acct. only. If we need their ops team to confirm the other deposits for other accts after getting clarification from Cachet, then we can send another inquiry to TBBK.

**Comment by lh12345** [comment] 2017-05-09 18:24
@john-cai Cachet's comments about all checks have settled except 3 - which 3 are they referring to?

**Comment by john-cai** [comment] 2017-05-09 18:25
sorry, not 3, i meant number 3 in the list above. the midwest one:

Midwest Benefits (x563) deposited check number: 0000230151 in the amount of $277.03 on 4/28

this was the original one in question

**Comment by lh12345** [comment] 2017-05-09 18:27
ok - got it. thanks!

**Comment by rachaelwoolen** [comment] 2017-05-09 19:04
@john-cai @lh12345 Just to clarify, Bancorp is saying they have no record of check the check to  Midwest Benefits (x563) deposited check number: 0000230151 in the amount of $277.03 on 4/28, or that it didn't clear?

**Comment by rachaelwoolen** [comment] 2017-05-09 19:18
I figured out the problem. The acceptance didn't go through. 

![screen shot 2017-05-09 at 12 17 11 pm](https://cloud.githubusercontent.com/assets/27706473/25868420/7a2f0a64-34b1-11e7-8476-ca08f1f1c72c.png)

**Comment by rachaelwoolen** [comment] 2017-05-09 19:58
Never mind. We think Catchet just reset the check so we could accept it again. Mystery still outstanding.

**Comment by melgeyer** [comment] 2017-05-09 20:02
I'm sure we'll hear from Cachet that they identified and reset the check, b/c we couldn't have missed the check if it was pending for a week. Our queue generally consists of one or two checks each day, which we review and approve many times per week. 

In the meantime though, is there a way for us to be alerted to an issue when a check that we've sent to Cachet doesn't make it to TBBK? Is there a report or alert we could get? I'm concerned that it was reported by a customer, especially since it's relying on a non-bank partner.

**Comment by melgeyer** [comment] 2017-05-09 20:07
From Cachet, explaining what occurred and why the check showed back up in the check review tool: 

The account number was not read initially by the scanning engine, probably because of the design on the check.  When this issue occurs were notified by a a job on our end that a transaction was accepted without an account number, at which time we would reach out to the customer and have them verify the account number.  We see these often with starter checks that have hand written account numbers, or in this case where a design, shadow, glare or a fold in the check has caused the scanning engine to cause a misread.  We are investigating why this process did not catch this check on the submission date.

As of now to resolve this issue, I have updated the account info for transaction 230 and it will need to be re-accepted on your end, and will go out on the next scheduled run time.

Big thanks to @jcai for establishing strong urgency with their team in reporting this issue, and getting the mystery resolved in a few hours. You're terrific!

**Comment by lh12345** [comment] 2017-05-09 23:14
@john-cai thanks for getting us the clarification from cachet. can we ask them for an ETA on providing root cause and next steps going forward to prevent such issues? also, to what extent are they confident that such design related issues are not tied to fake checks based on their experience? perhaps i can have a direct conversation with their team if that helps. thank you!

**Comment by melgeyer** [comment] 2017-05-10 16:40
We got the check reset by CheckReview and @john-cai spoke with Cachet today and confirmed that the check made it into the deposit file that got sent to TBBK last night.

Today though, the check deposit from 4/28 is still lingering in Pending. The new check seems to have already cleared and is in his available balance. 

How do we shake out the old one that is hanging out in Pending?

**Comment by john-cai** [comment] 2017-05-12 16:48
this one should be resolved. Cachet found out that a database setting prevented the job from running.

**Comment by melgeyer** [comment] 2017-05-12 17:01
Thanks, @john-cai for reporting back on the final resolution. The zen ticket for the customer correspondence is here: https://seedinc.zendesk.com/agent/tickets/805

For Mike @ Midwest: The erroneous pending check was removed, the check deposit was made to his account & appears in his current balance.

**Closed by melgeyer** 2017-05-12 17:01 UTC
Labels: Critical Priority
